# Mysql DataSource Config
spring:
    datasource:
        url: jdbc:mysql://rm-uf6yv1su2xshf4d453o.mysql.rds.aliyuncs.com:3306/mq-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: mqtt
        password: wcgBu4BwAAe6s__O7cdBzdRL-e4NhcAg
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    # rabbitmq Config
    rabbitmq:
        host: testing.ceegdev.com
        port: 5672
        username: admin
        password: Li=qYsaIg=KIc%d?2n5eGc6AZn4T!rkR
        virtual-host: /
        listener:
            simple:
                auto-startup: true
                acknowledge-mode: manual
                retry:
                    enabled: true
                    max-attempts: 3
                    initial-interval: 5000ms
                prefetch: 1
                concurrency: 1
                max-concurrency: 1
# mybatis plus
mybatis-plus:
    global-config:
        db-config:
            id-type: auto
        banner: false
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

